export const Customers = [{
  id: 1,
  name: "Carmen",
  rating: 5,
  review: "Delicious food and cozy atmosphere. I’ll be back soon!",
  img: "/Icons_assets/carmen.webp",
},
{
  id: 2,
  name: "Carlos",
  rating: 4,
  review: "Authentic flavors, though the service could be better.",
  img: "/Icons_assets/carlos.webp",
},
{
  id: 3,
  name: "Kevin",
  rating: 5,
  review: "Amazing experience, every dish was a delight.",
  img: "/Icons_assets/kevin.webp",
},
{
  id: 4,
  name: "Luisa",
  rating: 5,
  review: "Fresh ingredients and rich flavors. Highly recommended!",
  img: "/Icons_assets/luisa.webp",
},
{
  id: 5,
  name: "Arnold",
  rating: 4,
  review: "Great food but a bit crowded. Still worth it!",
  img: "/Icons_assets/arnold.webp",
},
{
  id: 6,
  name: "Melissa",
  rating: 5,
  review: "Perfect balance of spices and taste. Loved it!",
  img: "/Icons_assets/melissa.webp",
},
{
  id: 7,
  name: "Jordan",
  rating: 4,
  review: "Good food, though I wish the portions were bigger.",
  img: "/Icons_assets/jordan.webp",
},
{
  id: 8,
  name: "Lidia",
  rating: 5,
  review: "Exceptional Mediterranean cuisine. Will return!",
  img: "/Icons_assets/lidia.webp",
},
]